CREATE TABLE IF NOT EXISTS tasks
(
    id    BIGSERIAL PRIMARY KEY ,
    name  VARCHAR(200) NOT NULL,
    priority  INTEGER NOT NULL,
    year INTEGER NOT NULL,
    month INTEGER NOT NULL,
    day INTEGER NOT NULL,
    time  VARCHAR(200) NOT NULL,
    date VARCHAR(200) NOT NULL

    );